// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: order/order_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "order_service";

export enum OrderStatus {
  UNSPECIFIED = 0,
  CREATED = 1,
  CONFIRMED = 2,
  PREPARING = 3,
  DELIVERING = 4,
  COMPLETED = 5,
  CANCELLED = 6,
  UNRECOGNIZED = -1,
}

export function orderStatusFromJSON(object: any): OrderStatus {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return OrderStatus.UNSPECIFIED;
    case 1:
    case "CREATED":
      return OrderStatus.CREATED;
    case 2:
    case "CONFIRMED":
      return OrderStatus.CONFIRMED;
    case 3:
    case "PREPARING":
      return OrderStatus.PREPARING;
    case 4:
    case "DELIVERING":
      return OrderStatus.DELIVERING;
    case 5:
    case "COMPLETED":
      return OrderStatus.COMPLETED;
    case 6:
    case "CANCELLED":
      return OrderStatus.CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStatus.UNRECOGNIZED;
  }
}

export function orderStatusToJSON(object: OrderStatus): string {
  switch (object) {
    case OrderStatus.UNSPECIFIED:
      return "UNSPECIFIED";
    case OrderStatus.CREATED:
      return "CREATED";
    case OrderStatus.CONFIRMED:
      return "CONFIRMED";
    case OrderStatus.PREPARING:
      return "PREPARING";
    case OrderStatus.DELIVERING:
      return "DELIVERING";
    case OrderStatus.COMPLETED:
      return "COMPLETED";
    case OrderStatus.CANCELLED:
      return "CANCELLED";
    case OrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CreateOrderRequest {
  userId: string;
  items: OrderItemMessage[];
  address: string;
}

export interface CreateOrderResponse {
  order: OrderMessage | undefined;
}

export interface GetOrderByIdRequest {
  orderId: string;
}

export interface GetOrderByIdResponse {
  order: OrderMessage | undefined;
}

export interface GetOrdersByUserRequest {
  userId: string;
}

export interface GetOrdersByUserResponse {
  orders: OrderMessage[];
}

export interface UpdateOrderStatusRequest {
  orderId: string;
  status: OrderStatus;
}

export interface UpdateOrderStatusResponse {
  order: OrderMessage | undefined;
}

export interface OrderMessage {
  id: string;
  userId: string;
  items: OrderItemMessage[];
  status: OrderStatus;
  totalPrice: number;
  address: string;
  createdAt: string;
  updatedAt: string;
}

export interface OrderItemMessage {
  productId: string;
  name: string;
  quantity: number;
  price: number;
}

function createBaseCreateOrderRequest(): CreateOrderRequest {
  return { userId: "", items: [], address: "" };
}

export const CreateOrderRequest: MessageFns<CreateOrderRequest> = {
  encode(message: CreateOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    for (const v of message.items) {
      OrderItemMessage.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(OrderItemMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => OrderItemMessage.fromJSON(e)) : [],
      address: isSet(object.address) ? globalThis.String(object.address) : "",
    };
  },

  toJSON(message: CreateOrderRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderItemMessage.toJSON(e));
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(base?: I): CreateOrderRequest {
    return CreateOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(object: I): CreateOrderRequest {
    const message = createBaseCreateOrderRequest();
    message.userId = object.userId ?? "";
    message.items = object.items?.map((e) => OrderItemMessage.fromPartial(e)) || [];
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseCreateOrderResponse(): CreateOrderResponse {
  return { order: undefined };
}

export const CreateOrderResponse: MessageFns<CreateOrderResponse> = {
  encode(message: CreateOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order !== undefined) {
      OrderMessage.encode(message.order, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order = OrderMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse {
    return { order: isSet(object.order) ? OrderMessage.fromJSON(object.order) : undefined };
  },

  toJSON(message: CreateOrderResponse): unknown {
    const obj: any = {};
    if (message.order !== undefined) {
      obj.order = OrderMessage.toJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse>, I>>(base?: I): CreateOrderResponse {
    return CreateOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse>, I>>(object: I): CreateOrderResponse {
    const message = createBaseCreateOrderResponse();
    message.order = (object.order !== undefined && object.order !== null)
      ? OrderMessage.fromPartial(object.order)
      : undefined;
    return message;
  },
};

function createBaseGetOrderByIdRequest(): GetOrderByIdRequest {
  return { orderId: "" };
}

export const GetOrderByIdRequest: MessageFns<GetOrderByIdRequest> = {
  encode(message: GetOrderByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrderByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrderByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrderByIdRequest {
    return { orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "" };
  },

  toJSON(message: GetOrderByIdRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrderByIdRequest>, I>>(base?: I): GetOrderByIdRequest {
    return GetOrderByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderByIdRequest>, I>>(object: I): GetOrderByIdRequest {
    const message = createBaseGetOrderByIdRequest();
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseGetOrderByIdResponse(): GetOrderByIdResponse {
  return { order: undefined };
}

export const GetOrderByIdResponse: MessageFns<GetOrderByIdResponse> = {
  encode(message: GetOrderByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order !== undefined) {
      OrderMessage.encode(message.order, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrderByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrderByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order = OrderMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrderByIdResponse {
    return { order: isSet(object.order) ? OrderMessage.fromJSON(object.order) : undefined };
  },

  toJSON(message: GetOrderByIdResponse): unknown {
    const obj: any = {};
    if (message.order !== undefined) {
      obj.order = OrderMessage.toJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrderByIdResponse>, I>>(base?: I): GetOrderByIdResponse {
    return GetOrderByIdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderByIdResponse>, I>>(object: I): GetOrderByIdResponse {
    const message = createBaseGetOrderByIdResponse();
    message.order = (object.order !== undefined && object.order !== null)
      ? OrderMessage.fromPartial(object.order)
      : undefined;
    return message;
  },
};

function createBaseGetOrdersByUserRequest(): GetOrdersByUserRequest {
  return { userId: "" };
}

export const GetOrdersByUserRequest: MessageFns<GetOrdersByUserRequest> = {
  encode(message: GetOrdersByUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrdersByUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrdersByUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrdersByUserRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: GetOrdersByUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrdersByUserRequest>, I>>(base?: I): GetOrdersByUserRequest {
    return GetOrdersByUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrdersByUserRequest>, I>>(object: I): GetOrdersByUserRequest {
    const message = createBaseGetOrdersByUserRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetOrdersByUserResponse(): GetOrdersByUserResponse {
  return { orders: [] };
}

export const GetOrdersByUserResponse: MessageFns<GetOrdersByUserResponse> = {
  encode(message: GetOrdersByUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.orders) {
      OrderMessage.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrdersByUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrdersByUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orders.push(OrderMessage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrdersByUserResponse {
    return {
      orders: globalThis.Array.isArray(object?.orders) ? object.orders.map((e: any) => OrderMessage.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetOrdersByUserResponse): unknown {
    const obj: any = {};
    if (message.orders?.length) {
      obj.orders = message.orders.map((e) => OrderMessage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrdersByUserResponse>, I>>(base?: I): GetOrdersByUserResponse {
    return GetOrdersByUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrdersByUserResponse>, I>>(object: I): GetOrdersByUserResponse {
    const message = createBaseGetOrdersByUserResponse();
    message.orders = object.orders?.map((e) => OrderMessage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateOrderStatusRequest(): UpdateOrderStatusRequest {
  return { orderId: "", status: 0 };
}

export const UpdateOrderStatusRequest: MessageFns<UpdateOrderStatusRequest> = {
  encode(message: UpdateOrderStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateOrderStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateOrderStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateOrderStatusRequest {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      status: isSet(object.status) ? orderStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: UpdateOrderStatusRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.status !== 0) {
      obj.status = orderStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateOrderStatusRequest>, I>>(base?: I): UpdateOrderStatusRequest {
    return UpdateOrderStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateOrderStatusRequest>, I>>(object: I): UpdateOrderStatusRequest {
    const message = createBaseUpdateOrderStatusRequest();
    message.orderId = object.orderId ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseUpdateOrderStatusResponse(): UpdateOrderStatusResponse {
  return { order: undefined };
}

export const UpdateOrderStatusResponse: MessageFns<UpdateOrderStatusResponse> = {
  encode(message: UpdateOrderStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order !== undefined) {
      OrderMessage.encode(message.order, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateOrderStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateOrderStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order = OrderMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateOrderStatusResponse {
    return { order: isSet(object.order) ? OrderMessage.fromJSON(object.order) : undefined };
  },

  toJSON(message: UpdateOrderStatusResponse): unknown {
    const obj: any = {};
    if (message.order !== undefined) {
      obj.order = OrderMessage.toJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateOrderStatusResponse>, I>>(base?: I): UpdateOrderStatusResponse {
    return UpdateOrderStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateOrderStatusResponse>, I>>(object: I): UpdateOrderStatusResponse {
    const message = createBaseUpdateOrderStatusResponse();
    message.order = (object.order !== undefined && object.order !== null)
      ? OrderMessage.fromPartial(object.order)
      : undefined;
    return message;
  },
};

function createBaseOrderMessage(): OrderMessage {
  return { id: "", userId: "", items: [], status: 0, totalPrice: 0, address: "", createdAt: "", updatedAt: "" };
}

export const OrderMessage: MessageFns<OrderMessage> = {
  encode(message: OrderMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    for (const v of message.items) {
      OrderItemMessage.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.totalPrice !== 0) {
      writer.uint32(41).double(message.totalPrice);
    }
    if (message.address !== "") {
      writer.uint32(50).string(message.address);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.items.push(OrderItemMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.totalPrice = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderMessage {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => OrderItemMessage.fromJSON(e)) : [],
      status: isSet(object.status) ? orderStatusFromJSON(object.status) : 0,
      totalPrice: isSet(object.totalPrice) ? globalThis.Number(object.totalPrice) : 0,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: OrderMessage): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderItemMessage.toJSON(e));
    }
    if (message.status !== 0) {
      obj.status = orderStatusToJSON(message.status);
    }
    if (message.totalPrice !== 0) {
      obj.totalPrice = message.totalPrice;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderMessage>, I>>(base?: I): OrderMessage {
    return OrderMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderMessage>, I>>(object: I): OrderMessage {
    const message = createBaseOrderMessage();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.items = object.items?.map((e) => OrderItemMessage.fromPartial(e)) || [];
    message.status = object.status ?? 0;
    message.totalPrice = object.totalPrice ?? 0;
    message.address = object.address ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseOrderItemMessage(): OrderItemMessage {
  return { productId: "", name: "", quantity: 0, price: 0 };
}

export const OrderItemMessage: MessageFns<OrderItemMessage> = {
  encode(message: OrderItemMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    if (message.price !== 0) {
      writer.uint32(33).double(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderItemMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderItemMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.price = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderItemMessage {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
    };
  },

  toJSON(message: OrderItemMessage): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderItemMessage>, I>>(base?: I): OrderItemMessage {
    return OrderItemMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderItemMessage>, I>>(object: I): OrderItemMessage {
    const message = createBaseOrderItemMessage();
    message.productId = object.productId ?? "";
    message.name = object.name ?? "";
    message.quantity = object.quantity ?? 0;
    message.price = object.price ?? 0;
    return message;
  },
};

export type OrderServiceService = typeof OrderServiceService;
export const OrderServiceService = {
  createOrder: {
    path: "/order_service.OrderService/CreateOrder" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateOrderRequest): Buffer => Buffer.from(CreateOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateOrderRequest => CreateOrderRequest.decode(value),
    responseSerialize: (value: CreateOrderResponse): Buffer => Buffer.from(CreateOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateOrderResponse => CreateOrderResponse.decode(value),
  },
  getOrderById: {
    path: "/order_service.OrderService/GetOrderById" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetOrderByIdRequest): Buffer => Buffer.from(GetOrderByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetOrderByIdRequest => GetOrderByIdRequest.decode(value),
    responseSerialize: (value: GetOrderByIdResponse): Buffer =>
      Buffer.from(GetOrderByIdResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetOrderByIdResponse => GetOrderByIdResponse.decode(value),
  },
  getOrdersByUser: {
    path: "/order_service.OrderService/GetOrdersByUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetOrdersByUserRequest): Buffer =>
      Buffer.from(GetOrdersByUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetOrdersByUserRequest => GetOrdersByUserRequest.decode(value),
    responseSerialize: (value: GetOrdersByUserResponse): Buffer =>
      Buffer.from(GetOrdersByUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetOrdersByUserResponse => GetOrdersByUserResponse.decode(value),
  },
  updateOrderStatus: {
    path: "/order_service.OrderService/UpdateOrderStatus" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateOrderStatusRequest): Buffer =>
      Buffer.from(UpdateOrderStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateOrderStatusRequest => UpdateOrderStatusRequest.decode(value),
    responseSerialize: (value: UpdateOrderStatusResponse): Buffer =>
      Buffer.from(UpdateOrderStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateOrderStatusResponse => UpdateOrderStatusResponse.decode(value),
  },
} as const;

export interface OrderServiceServer extends UntypedServiceImplementation {
  createOrder: handleUnaryCall<CreateOrderRequest, CreateOrderResponse>;
  getOrderById: handleUnaryCall<GetOrderByIdRequest, GetOrderByIdResponse>;
  getOrdersByUser: handleUnaryCall<GetOrdersByUserRequest, GetOrdersByUserResponse>;
  updateOrderStatus: handleUnaryCall<UpdateOrderStatusRequest, UpdateOrderStatusResponse>;
}

export interface OrderServiceClient extends Client {
  createOrder(
    request: CreateOrderRequest,
    callback: (error: ServiceError | null, response: CreateOrderResponse) => void,
  ): ClientUnaryCall;
  createOrder(
    request: CreateOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateOrderResponse) => void,
  ): ClientUnaryCall;
  createOrder(
    request: CreateOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateOrderResponse) => void,
  ): ClientUnaryCall;
  getOrderById(
    request: GetOrderByIdRequest,
    callback: (error: ServiceError | null, response: GetOrderByIdResponse) => void,
  ): ClientUnaryCall;
  getOrderById(
    request: GetOrderByIdRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetOrderByIdResponse) => void,
  ): ClientUnaryCall;
  getOrderById(
    request: GetOrderByIdRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetOrderByIdResponse) => void,
  ): ClientUnaryCall;
  getOrdersByUser(
    request: GetOrdersByUserRequest,
    callback: (error: ServiceError | null, response: GetOrdersByUserResponse) => void,
  ): ClientUnaryCall;
  getOrdersByUser(
    request: GetOrdersByUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetOrdersByUserResponse) => void,
  ): ClientUnaryCall;
  getOrdersByUser(
    request: GetOrdersByUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetOrdersByUserResponse) => void,
  ): ClientUnaryCall;
  updateOrderStatus(
    request: UpdateOrderStatusRequest,
    callback: (error: ServiceError | null, response: UpdateOrderStatusResponse) => void,
  ): ClientUnaryCall;
  updateOrderStatus(
    request: UpdateOrderStatusRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateOrderStatusResponse) => void,
  ): ClientUnaryCall;
  updateOrderStatus(
    request: UpdateOrderStatusRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateOrderStatusResponse) => void,
  ): ClientUnaryCall;
}

export const OrderServiceClient = makeGenericClientConstructor(
  OrderServiceService,
  "order_service.OrderService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OrderServiceClient;
  service: typeof OrderServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
